[build]
  base = "backend"
  command = "npm install && npm run build" # Adjust as per your backend setup
  publish = "dist" # Set to your frontend build directory if applicable

[functions]
  directory = "netlify/functions"